version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/softpet
    depends_on:
      - db
    
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: softpet
    volumes:
      - postgres_data:/var/lib/postgresql/DATABASE_URL

volumes:
  postgres_data: