services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/softpet
    depends_on:
      - db
    
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "softpet"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "softpet"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: